### ISSUE TITLE
实习二Management无法用auto传递参数

### ISSUE THREAD

**Issue by Otboundary** [HereIsZephyrus/MyCoding#3]
auto不能使用

>
<img width="1280" alt="屏幕截图 2023-04-05 082155" src="https://user-images.githubusercontent.com/126947058/229950666-ebe6d196-1a13-43b0-aff2-ddefe5666090.png">
<img width="470" alt="屏幕截图 2023-04-05 082242" src="https://user-images.githubusercontent.com/126947058/229950761-4b01f859-4bcb-41d1-a028-ae2791b7da5f.png">

**Comment by HereIsZephyrus** [comment]
这个问题是由于你的编译器不支持C++20特性导致的
在C++20中支持使用auto传递参数，但是目前还不能用于推导数组类型，同时我发现auto仍然不能用以定义函数类型即以下两种定义不合法：
auto f(){}
auto a[];
此处auto应被解析的类型是Student* 可以替换后重新尝试

最后，请在标题说清楚问题，并不要直接交两个截图……粘贴代码、错误信息和链接是更好的选择。
Channing Tong
