### ISSUE TITLE
实习二Calculator头文件冲突与在VS中的编译错误

### ISSUE THREAD

**Issue by Otboundary** [HereIsZephyrus/MyCoding#4]
#endif // !_HAS_CXX20

    _CONSTEXPR20 void _Compat(const _String_const_iterator& _Right) const noexcept {
        // test for compatible iterator pair
#if _ITERATOR_DEBUG_LEVEL >= 1
        _STL_VERIFY(this->_Getcont() == _Right._Getcont(), "string iterators incompatible (e.g."
                                                           " point to different string instances)");
#else // ^^^ _ITERATOR_DEBUG_LEVEL >= 1 ^^^ // vvv _ITERATOR_DEBUG_LEVEL == 0 vvv
        (void) _Right;
#endif // _ITERATOR_DEBUG_LEVEL
    }

#if _ITERATOR_DEBUG_LEVEL >= 1
    friend _CONSTEXPR20 void _Verify_range(
        const _String_const_iterator& _First, const _String_const_iterator& _Last) noexcept {
        _STL_VERIFY(_First._Getcont() == _Last._Getcont(), "string iterators in range are from different containers");
        _STL_VERIFY(_First._Ptr <= _Last._Ptr, "string iterator range transposed");
    }

#if _ITERATOR_DEBUG_LEVEL >= 1
        _Verify_offset(_Off);
#endif // _ITERATOR_DEBUG_LEVEL >= 1
        _Ptr += _Off;
        return *this;
    }

    _NODISCARD _CONSTEXPR20 _String_const_iterator operator+(const difference_type _Off) const noexcept {
        _String_const_iterator _Tmp = *this;
        _Tmp += _Off;
        return _Tmp;
    }

    _NODISCARD_FRIEND _CONSTEXPR20 _String_const_iterator operator+(
        const difference_type _Off, _String_const_iterator _Next) noexcept {
        _Next += _Off;
        return _Next;
    }

    _CONSTEXPR20 _String_const_iterator& operator-=(const difference_type _Off) noexcept {
        return *this += -_Off;
    }

    _NODISCARD _CONSTEXPR20 _String_const_iterator operator-(const difference_type _Off) const noexcept {
        _String_const_iterator _Tmp = *this;
        _Tmp -= _Off;
        return _Tmp;
    }

    _NODISCARD _CONSTEXPR20 difference_type operator-(const _String_const_iterator& _Right) const noexcept {
        _Compat(_Right);
        return _Ptr - _Right._Ptr;
    }

    _NODISCARD _CONSTEXPR20 reference operator[](const difference_type _Off) const noexcept {
        return *(*this + _Off);
    }

    _NODISCARD _CONSTEXPR20 bool operator==(const _String_const_iterator& _Right) const noexcept {
        _Compat(_Right);
        return _Ptr == _Right._Ptr;
    }

if (*p == '-' || *p == '+') {
            if (p == Expr.begin() || (!Back_Bracket(*(p - 1)) && (*(p - 1) != '!') && (*(p - 1) < '0' || *(p - 1) > '9'))) {
                //若不是后括号或幂或数字则不是合法双目运算符
                if (*p == '-')  flag = -1;
                if (*p == '+')  flag = 1;
                p++;
                //        cout<<"flag"<<endl;
                //        system("pause");
                continue;
            }
        }

int main() {
    cin >> Expr;
    while (!(Expr.length() == 1 && Expr[0] == '0')) {
        Expr = '(' + Expr + ')';//在表达式两端加上括号用于简化处理
        if (!Valid(Expr))
            cout << "It is not a valid expression!" << endl;
        else
            cout << Solve(Expr) << endl;//求解运算符
        cin >> Expr;
    }
    cin.get();
    cin.get();
    return 0;
}

**Comment by HereIsZephyrus** [comment]
已修复头文件冲突问题，
加入#pragma once
然而在VScode中报错能编译，貌似是task.json的问题，还在研究
正在解决报错问题

**Comment by HereIsZephyrus** [comment]
我发现了！
` if` (p == '-' || p == '+') {
写错了，应该改为
` if` (*p == '-' || *p == '+') {


---
不对啊你是不是手滑把我代码改了啊我回头看了一眼是对的 @Otboundary

**Comment by HereIsZephyrus** [comment]
转载自[CSDN](https://blog.csdn.net/yx20130919/article/details/52134735?spm=1001.2101.3001.6650.12&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7ERate-12-52134735-blog-50992298.235%5Ev27%5Epc_relevant_default_base1&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7ERate-12-52134735-blog-50992298.235%5Ev27%5Epc_relevant_default_base1&utm_relevant_index=13)的一条经验

> 
在.cpp文件中声明变量，然后建一个头文件(.h文件)在所有的变量声明前加上extern，注意这里不要对变量进行的初始化。然后在其他需要使用全局变量的.cpp文件中包含.h文件。编译器会为.cpp生成目标文件，然后链接时，如果该.cpp文件使用了全局变量，链接器就会链接到此.cpp文件 。

**Comment by HereIsZephyrus** [comment]
我知道为什么VScode把#pragma once报错了
我在下午改的时候将#pragma once写在main.cpp里，会报错但是可以运行
研究了一下，发现应该将#pragma once写在.h里，这时再运行main.cpp就不会报错了
现在已修复

**Comment by HMBlankcat** [comment]
amazing
